package View;

import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JTextArea;
import com.toedter.calendar.JDateChooser;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author matijaselak
 */
public class GUIComponent extends javax.swing.JFrame {

    private static final String COMMA_DELIMITER = ",";
    private static final String NEW_LINE_SEPARATOR = "\n";
    public JTextArea textArea;
    SimpleDateFormat format = new SimpleDateFormat("yyyy,MM,dd");

    /**
     * Creates new form TestGUI
     */
    public GUIComponent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateFood = new com.toedter.calendar.JDateChooser();
        cmbFoods = new javax.swing.JComboBox<>();
        quantitySpinner = new javax.swing.JSpinner();
        btnAddNewFood = new javax.swing.JButton();
        lblQuantity = new javax.swing.JLabel();
        lblSelectFood = new javax.swing.JLabel();
        lblDateFood = new javax.swing.JLabel();
        lblLogFood = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnAddNewRecipe = new javax.swing.JButton();
        lblLogWeight = new javax.swing.JLabel();
        lblDateWeight = new javax.swing.JLabel();
        jDateWeight = new com.toedter.calendar.JDateChooser();
        textFieldWeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        btnViewLog = new javax.swing.JButton();
        btnLogWeight = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        calDateLabel = new javax.swing.JLabel();
        calLimitLabel = new javax.swing.JLabel();
        jDateCalorieField = new com.toedter.calendar.JDateChooser();
        calorieTextField = new javax.swing.JTextField();
        logCalButton = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setToolTipText("dsfrg");

        jDateFood.setDateFormatString("yyyy MM d");

        cmbFoods.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cmbFoods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFoods.setMinimumSize(new java.awt.Dimension(72, 36));
        cmbFoods.setPreferredSize(new java.awt.Dimension(72, 36));

        quantitySpinner.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));
        quantitySpinner.setToolTipText("");
        quantitySpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAddNewFood.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnAddNewFood.setText("Add new food");
        btnAddNewFood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNewFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewFoodActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantity.setText("Quantity:");

        lblSelectFood.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        lblSelectFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectFood.setText("Select food:");

        lblDateFood.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        lblDateFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateFood.setText("Select date:");

        lblLogFood.setFont(new java.awt.Font("Lucida Grande", 1, 35)); // NOI18N
        lblLogFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogFood.setText("LOG FOOD");
        lblLogFood.setAlignmentX(0.5F);

        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnSave.setText("Log");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddNewRecipe.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnAddNewRecipe.setText("Add new recipe");
        btnAddNewRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewRecipeActionPerformed(evt);
            }
        });

        lblLogWeight.setFont(new java.awt.Font("Lucida Grande", 1, 35)); // NOI18N
        lblLogWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogWeight.setText("LOG WEIGHT");
        lblLogWeight.setAlignmentX(0.5F);

        lblDateWeight.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        lblDateWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateWeight.setText("Select date:");

        jDateWeight.setDateFormatString("yyyy MM d");

        textFieldWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldWeight.setText("Enter your weight");
        textFieldWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldWeightFocusGained(evt);
            }
        });

        lblWeight.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeight.setText("Weight:");
        lblWeight.setToolTipText("");

        btnViewLog.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnViewLog.setText("View Log");
        btnViewLog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLogActionPerformed(evt);
            }
        });

        btnLogWeight.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnLogWeight.setText("Log Weight");
        btnLogWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogWeightActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 35)); // NOI18N
        jLabel1.setText("LOG CALORIES LIMIT");

        calDateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        calDateLabel.setText("Select date:");

        calLimitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        calLimitLabel.setText("Calorie limit:");

        jDateCalorieField.setDateFormatString("yyyy MM dd");

        calorieTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calorieTextField.setText("Enter your calories limit");
        calorieTextField.setToolTipText("");
        calorieTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calorieTextFieldFocusGained(evt);
            }
        });

        logCalButton.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        logCalButton.setText("Log Calories");
        logCalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logCalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogFood, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblDateFood, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateFood, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblSelectFood, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNewRecipe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddNewFood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnLogWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logCalButton)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblLogWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calDateLabel)
                            .addComponent(calLimitLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calorieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateCalorieField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewLog, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblLogFood, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectFood)
                    .addComponent(btnAddNewFood))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateFood)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddNewRecipe)
                        .addComponent(jDateFood, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateWeight)
                    .addComponent(calDateLabel)
                    .addComponent(jDateWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateCalorieField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWeight)
                    .addComponent(calLimitLabel)
                    .addComponent(calorieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogWeight)
                    .addComponent(logCalButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnViewLog)
                .addGap(26, 26, 26))
        );

        jDateFood.getAccessibleContext().setAccessibleName("foodDateBox");
        cmbFoods.getAccessibleContext().setAccessibleName("foodMenu");
        quantitySpinner.getAccessibleContext().setAccessibleName("foodQuantity");
        btnAddNewFood.getAccessibleContext().setAccessibleName("newFoodButton");
        lblQuantity.getAccessibleContext().setAccessibleName("foodQuantityLabel");
        lblSelectFood.getAccessibleContext().setAccessibleName("selectFoodLabel");
        lblDateFood.getAccessibleContext().setAccessibleName("dailyDateLabel");
        lblLogFood.getAccessibleContext().setAccessibleName("logFoodLabel");
        btnSave.getAccessibleContext().setAccessibleName("dailyLogButton");
        btnAddNewRecipe.getAccessibleContext().setAccessibleName("newRecipeButton");
        lblLogWeight.getAccessibleContext().setAccessibleName("logWeightLabel");
        lblDateWeight.getAccessibleContext().setAccessibleName("weightDateLabel");
        jDateWeight.getAccessibleContext().setAccessibleName("weightDateBox");
        textFieldWeight.getAccessibleContext().setAccessibleName("weightTextField");
        lblWeight.getAccessibleContext().setAccessibleName("weightLabel");
        btnViewLog.getAccessibleContext().setAccessibleName("viewLogButton");
        btnLogWeight.getAccessibleContext().setAccessibleName("logWeightButton");

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 0, 50)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("DIET MANAGER");
        lblHeader.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogActionPerformed

    }//GEN-LAST:event_btnViewLogActionPerformed


    private void btnAddNewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewRecipeActionPerformed

    }//GEN-LAST:event_btnAddNewRecipeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddNewFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewFoodActionPerformed

    }//GEN-LAST:event_btnAddNewFoodActionPerformed

    private void logCalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logCalButtonActionPerformed

    }//GEN-LAST:event_logCalButtonActionPerformed

    private void btnLogWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogWeightActionPerformed

    }//GEN-LAST:event_btnLogWeightActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void textFieldWeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldWeightFocusGained

    }//GEN-LAST:event_textFieldWeightFocusGained

    private void calorieTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calorieTextFieldFocusGained

    }//GEN-LAST:event_calorieTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIComponent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddNewFood;
    public javax.swing.JButton btnAddNewRecipe;
    public javax.swing.JButton btnLogWeight;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewLog;
    private javax.swing.JLabel calDateLabel;
    private javax.swing.JLabel calLimitLabel;
    public javax.swing.JTextField calorieTextField;
    public javax.swing.JComboBox<String> cmbFoods;
    public com.toedter.calendar.JDateChooser jDateCalorieField;
    public com.toedter.calendar.JDateChooser jDateFood;
    public com.toedter.calendar.JDateChooser jDateWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateFood;
    private javax.swing.JLabel lblDateWeight;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogFood;
    private javax.swing.JLabel lblLogWeight;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSelectFood;
    private javax.swing.JLabel lblWeight;
    public javax.swing.JButton logCalButton;
    public javax.swing.JSpinner quantitySpinner;
    public javax.swing.JTextField textFieldWeight;
    // End of variables declaration//GEN-END:variables
}
